drop database if exists fb;
create database fb;

use fb;

DROP TABLE IF EXISTS T_CASE;

DROP TABLE IF EXISTS T_LOG_TEXT;
DROP TABLE IF EXISTS T_SAMPLE;
DROP TABLE IF EXISTS T_SUITE;
DROP TABLE IF EXISTS T_LOG;
CREATE TABLE T_CASE(
  ID varchar(40) PRIMARY KEY,
  NAME TEXT NOT NULL,
  SUITEID TEXT NOT NULL
);
CREATE TABLE T_LOG(
  ID varchar(40) PRIMARY KEY,
  NAME TEXT NOT NULL,
  GEN TEXT NOT NULL
);
CREATE TABLE T_SAMPLE(
  ID SERIAL PRIMARY KEY,
  STATUS TEXT NOT NULL,
  NAME TEXT NOT NULL,
  CASEID TEXT NOT NULL,
  LOGID TEXT NOT NULL
);
CREATE TABLE T_SUITE(
  ID varchar(40) PRIMARY KEY,
  NAME TEXT NOT NULL,
  PARENTID TEXT,
  SOURCE TEXT
);
